version: '3.7'

services:
    php:
        build:
            context: .
            target: php-base
        volumes:
            - ./src:/var/www/src
        ports:
            - "8080:80"
        restart: "no"